name: fnf_guest_list
description: A flutter app

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.20.0-nullsafety.3
  # Import the provider package.
  provider: ^4.0.2
  intl:
  http: ^0.12.0+4
  battery: ^0.3.1+9
  row_collection: ^0.2.4
  flutter_typeahead: ^1.8.0
  equatable: ^1.1.1
  flutter_bloc: ^3.2.0
  flutter_staggered_animations: ^0.1.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/gearhead-pink.png"

flutter:
  uses-material-design: true
  assets:
    - assets/gearhead-heart.svg
    - assets/gearhead-ticket.svg
    - assets/gearhead-pink.svg
    - assets/gearhead-white.png
  fonts:
    - family: Corben
      fonts:
        - asset: fonts/Corben/Corben-Bold.ttf
          weight: 700
    - family: Shanhie
      fonts:
        - asset: fonts/Shanhie/shanhie.ttf
          weight: 500
    - family: RedRock
      fonts:
        - asset: fonts/RedRock/RedRock.ttf
          weight: 500

