name: provider_shopper
description: A shopping app sample that uses Provider for state management.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.3
  # Import the provider package.
  provider: ^4.0.2
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/gearhead-heart.svg
    - assets/gearhead-white.png
  fonts:
    - family: Corben
      fonts:
        - asset: fonts/Corben/Corben-Bold.ttf
          weight: 700
    - family: Shanhie
      fonts:
        - asset: fonts/Shanhie/shanhie.ttf
          weight: 500
    - family: RedRock
      fonts:
        - asset: fonts/RedRock/RedRock.ttf
          weight: 500

